### ISSUE TITLE
Does not appear to be working with WSL.

### ISSUE THREAD

**Issue by didinele** [stripe/vscode-stripe#137]
Consistently getting
> Cannot activate the 'Stripe' extension because it depends on the 'Git' extension, which is not loaded. Would you like to reload the window to load the extension?

Reloading the Window does not fix the issue.

This appears to be because the extension is installed "locally", and cannot be installed into the WSL remote, as highlighted in the [VSCode WSL documentation](https://code.visualstudio.com/docs/remote/wsl#_managing-extensions):

![image](https://sucks-to-b.eu/GD4AeA.png)

**Comment by bbangert** [comment]
Also doesn't work in Remote: SSH for the same reason.

**Comment by nfm** [comment]
I'm hitting this too in Remote: Containers.

**Comment by GavinRay97** [comment]
I get this as well -- This extension looks really amazing but since I do all development within WSL for unix-tooling compatibility purposes (developing on Windows is painful), I don't seem to able to use it 🙁 

Would be grateful for a fix

![image](https://user-images.githubusercontent.com/26604994/107284009-2281c500-6a2b-11eb-92a8-762fde6ee036.png)

**Comment by edicristofaro** [comment]
I have this issue as well. Getting `Cannot activate the 'Stripe' extension because it depends on the 'Git' extension, which is not loaded. Would you like to reload the window to load the extension?` when installing locally - vscode january 2021 stable, wsl2. I also tried to work around by installing on the remote with `wget https://github.com/stripe/vscode-stripe/releases/download/v1.7.0/vscode-stripe-1.7.0.vsix && code --install-extension vscode-stripe-1.7.0.vsix` but it complains about not being installed locally. Doing that loops back to the original issue. Happy to do some logging if its useful.

**Comment by ImedAdel** [comment]
I get the same issue when using the remote extension on Ubuntu, so it's not just limited to WSL.

**Comment by AgentIvan** [comment]
Please explain how to use your extension in windows

**Comment by didinele** [comment]
Just tested today. Uncertain when it was fixed but I can confirm that it does work under WSL2 now!

If it also works for the folks that had trouble with it in SSH and containers (@bbangert, @nfm respectively) I can safely close this.

**Comment by NicholasG04** [comment]
Fixed by #159 which removed dependency on VSCode Git extension.

**Comment by vcheung-stripe** [comment]
@didinele, thanks for confirming this in WSL! I'm glad it's fixed for you.

@bbangert @nfm and any folks still experiencing issues in SSH and containers, could you try again on the latest version?

**Comment by nfm** [comment]
Thanks @vcheung-stripe - I can now load and activate the extension under devcontainers!

I'm hitting a new issue now (getting a `Failed to start 'stripe listen' process` when clicking "Start streaming events", despite having `stripe` installed, authed and working from a VSCode terminal) but this might be misconfiguration on my part - will dig into it an open a new issue if I can't figure it out.

**Comment by bbangert** [comment]
@vcheung-stripe Just tried it, it works great via SSH now. Thanks!

**Comment by lbragile** [comment]
I can't seem to **trigger new default event** using the extension in VSCode WSL2 as I see:

![image](https://user-images.githubusercontent.com/65437893/169732424-c82a73e5-f084-4762-a7e2-6c5dd9aa6750.png)

Even though I see that it is properly listening:
![image](https://user-images.githubusercontent.com/65437893/169732686-9c25ed38-ee6b-47ea-ad00-2facd0aac341.png)

Also, events do get passed to it, so communication/connection is present.

Text for better accessibility:
```
Warning: Failed to retrieve supported triggered event list dynamically: Error: 14 UNAVAILABLE: No connection established
Triggering event checkout.session.completed...

Failed to trigger event: checkout.session.completed. No connection established
```

I would like to trigger events to avoid having to manually go through the process during development for every update.

Any ideas?
